/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as QuadrantRouteImport } from './routes/quadrant'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as PrevisioRouteImport } from './routes/previsio'
import { Route as IngestaRouteImport } from './routes/ingesta'
import { Route as IncidenciesRouteImport } from './routes/incidencies'
import { Route as DadesRouteImport } from './routes/dades'
import { Route as IndexRouteImport } from './routes/index'

const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrantRoute = QuadrantRouteImport.update({
  id: '/quadrant',
  path: '/quadrant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisioRoute = PrevisioRouteImport.update({
  id: '/previsio',
  path: '/previsio',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestaRoute = IngestaRouteImport.update({
  id: '/ingesta',
  path: '/ingesta',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidenciesRoute = IncidenciesRouteImport.update({
  id: '/incidencies',
  path: '/incidencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DadesRoute = DadesRouteImport.update({
  id: '/dades',
  path: '/dades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dades': typeof DadesRoute
  '/incidencies': typeof IncidenciesRoute
  '/ingesta': typeof IngestaRoute
  '/previsio': typeof PrevisioRoute
  '/professionals': typeof ProfessionalsRoute
  '/quadrant': typeof QuadrantRoute
  '/reporting': typeof ReportingRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dades': typeof DadesRoute
  '/incidencies': typeof IncidenciesRoute
  '/ingesta': typeof IngestaRoute
  '/previsio': typeof PrevisioRoute
  '/professionals': typeof ProfessionalsRoute
  '/quadrant': typeof QuadrantRoute
  '/reporting': typeof ReportingRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dades': typeof DadesRoute
  '/incidencies': typeof IncidenciesRoute
  '/ingesta': typeof IngestaRoute
  '/previsio': typeof PrevisioRoute
  '/professionals': typeof ProfessionalsRoute
  '/quadrant': typeof QuadrantRoute
  '/reporting': typeof ReportingRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dades'
    | '/incidencies'
    | '/ingesta'
    | '/previsio'
    | '/professionals'
    | '/quadrant'
    | '/reporting'
    | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dades'
    | '/incidencies'
    | '/ingesta'
    | '/previsio'
    | '/professionals'
    | '/quadrant'
    | '/reporting'
    | '/simulador'
  id:
    | '__root__'
    | '/'
    | '/dades'
    | '/incidencies'
    | '/ingesta'
    | '/previsio'
    | '/professionals'
    | '/quadrant'
    | '/reporting'
    | '/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DadesRoute: typeof DadesRoute
  IncidenciesRoute: typeof IncidenciesRoute
  IngestaRoute: typeof IngestaRoute
  PrevisioRoute: typeof PrevisioRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  QuadrantRoute: typeof QuadrantRoute
  ReportingRoute: typeof ReportingRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadrant': {
      id: '/quadrant'
      path: '/quadrant'
      fullPath: '/quadrant'
      preLoaderRoute: typeof QuadrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsio': {
      id: '/previsio'
      path: '/previsio'
      fullPath: '/previsio'
      preLoaderRoute: typeof PrevisioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingesta': {
      id: '/ingesta'
      path: '/ingesta'
      fullPath: '/ingesta'
      preLoaderRoute: typeof IngestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidencies': {
      id: '/incidencies'
      path: '/incidencies'
      fullPath: '/incidencies'
      preLoaderRoute: typeof IncidenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dades': {
      id: '/dades'
      path: '/dades'
      fullPath: '/dades'
      preLoaderRoute: typeof DadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DadesRoute: DadesRoute,
  IncidenciesRoute: IncidenciesRoute,
  IngestaRoute: IngestaRoute,
  PrevisioRoute: PrevisioRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  QuadrantRoute: QuadrantRoute,
  ReportingRoute: ReportingRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
